/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminPensyaRouteImport } from './routes/admin-pensya'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SalasRouteImport } from './routes/salas'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedAlertasRouteImport } from './routes/_authenticated/alertas'
import { Route as AuthenticatedCadastrosRouteImport } from './routes/_authenticated/cadastros'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedContratosRouteImport } from './routes/_authenticated/contratos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedIndicadoresRouteImport } from './routes/_authenticated/indicadores'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedMeuFinanceiroRouteImport } from './routes/_authenticated/meu-financeiro'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedSublocacaoRouteImport } from './routes/_authenticated/sublocacao'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AssinarTokenRouteImport } from './routes/assinar.$token'
import { Route as CadastroTokenRouteImport } from './routes/cadastro.$token'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalDiarioRouteImport } from './routes/portal.diario'
import { Route as PortalEvolucaoRouteImport } from './routes/portal.evolucao'
import { Route as PortalFinanceiroRouteImport } from './routes/portal.financeiro'
import { Route as PortalRelatoriosRouteImport } from './routes/portal.relatorios'
import { Route as ProcessoPublicoTokenRouteImport } from './routes/processo-publico.$token'
import { Route as SalasTokenRouteImport } from './routes/salas.$token'
import { Route as AuthenticatedCadastrosModelosRouteImport } from './routes/_authenticated/cadastros_.modelos'
import { Route as AuthenticatedConfiguracoesIndexRouteImport } from './routes/_authenticated/configuracoes.index'
import { Route as AuthenticatedConfiguracoesBateriasRouteImport } from './routes/_authenticated/configuracoes.baterias'
import { Route as AuthenticatedConfiguracoesIaRouteImport } from './routes/_authenticated/configuracoes.ia'
import { Route as AuthenticatedConfiguracoesInstrumentosRouteImport } from './routes/_authenticated/configuracoes.instrumentos'
import { Route as AuthenticatedConfiguracoesProtocolosRouteImport } from './routes/_authenticated/configuracoes.protocolos'
import { Route as AuthenticatedConfiguracoesRecursosRouteImport } from './routes/_authenticated/configuracoes.recursos'
import { Route as AuthenticatedConfiguracoesReferenciasRouteImport } from './routes/_authenticated/configuracoes.referencias'
import { Route as AuthenticatedPacientesIndexRouteImport } from './routes/_authenticated/pacientes.index'
import { Route as AuthenticatedPacientesIdRouteImport } from './routes/_authenticated/pacientes.$id'
import { Route as AuthenticatedProcessosIndexRouteImport } from './routes/_authenticated/processos.index'
import { Route as AuthenticatedProcessosIdRouteImport } from './routes/_authenticated/processos.$id'
import { Route as EquipeConviteTokenRouteImport } from './routes/equipe_.convite.$token'
import { Route as PortalConviteTokenRouteImport } from './routes/portal_.convite.$token'
import { Route as ApiPublicWebhooksInfinitepayRouteImport } from './routes/api/public/webhooks/infinitepay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPensyaRoute = AdminPensyaRouteImport.update({
  id: '/admin-pensya',
  path: '/admin-pensya',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SalasRoute = SalasRouteImport.update({
  id: '/salas',
  path: '/salas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertasRoute = AuthenticatedAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCadastrosRoute = AuthenticatedCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratosRoute = AuthenticatedContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIndicadoresRoute =
  AuthenticatedIndicadoresRouteImport.update({
    id: '/indicadores',
    path: '/indicadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeuFinanceiroRoute =
  AuthenticatedMeuFinanceiroRouteImport.update({
    id: '/meu-financeiro',
    path: '/meu-financeiro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSublocacaoRoute = AuthenticatedSublocacaoRouteImport.update({
  id: '/sublocacao',
  path: '/sublocacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AssinarTokenRoute = AssinarTokenRouteImport.update({
  id: '/assinar/$token',
  path: '/assinar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroTokenRoute = CadastroTokenRouteImport.update({
  id: '/cadastro/$token',
  path: '/cadastro/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDiarioRoute = PortalDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEvolucaoRoute = PortalEvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFinanceiroRoute = PortalFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => PortalRoute,
} as any)
const PortalRelatoriosRoute = PortalRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => PortalRoute,
} as any)
const ProcessoPublicoTokenRoute = ProcessoPublicoTokenRouteImport.update({
  id: '/processo-publico/$token',
  path: '/processo-publico/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SalasTokenRoute = SalasTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => SalasRoute,
} as any)
const AuthenticatedCadastrosModelosRoute =
  AuthenticatedCadastrosModelosRouteImport.update({
    id: '/cadastros_/modelos',
    path: '/cadastros/modelos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesIndexRoute =
  AuthenticatedConfiguracoesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesBateriasRoute =
  AuthenticatedConfiguracoesBateriasRouteImport.update({
    id: '/baterias',
    path: '/baterias',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesIaRoute =
  AuthenticatedConfiguracoesIaRouteImport.update({
    id: '/ia',
    path: '/ia',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesInstrumentosRoute =
  AuthenticatedConfiguracoesInstrumentosRouteImport.update({
    id: '/instrumentos',
    path: '/instrumentos',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesProtocolosRoute =
  AuthenticatedConfiguracoesProtocolosRouteImport.update({
    id: '/protocolos',
    path: '/protocolos',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesRecursosRoute =
  AuthenticatedConfiguracoesRecursosRouteImport.update({
    id: '/recursos',
    path: '/recursos',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesReferenciasRoute =
  AuthenticatedConfiguracoesReferenciasRouteImport.update({
    id: '/referencias',
    path: '/referencias',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedPacientesIndexRoute =
  AuthenticatedPacientesIndexRouteImport.update({
    id: '/pacientes/',
    path: '/pacientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPacientesIdRoute =
  AuthenticatedPacientesIdRouteImport.update({
    id: '/pacientes/$id',
    path: '/pacientes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcessosIndexRoute =
  AuthenticatedProcessosIndexRouteImport.update({
    id: '/processos/',
    path: '/processos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcessosIdRoute =
  AuthenticatedProcessosIdRouteImport.update({
    id: '/processos/$id',
    path: '/processos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const EquipeConviteTokenRoute = EquipeConviteTokenRouteImport.update({
  id: '/equipe_/convite/$token',
  path: '/equipe/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalConviteTokenRoute = PortalConviteTokenRouteImport.update({
  id: '/portal_/convite/$token',
  path: '/portal/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksInfinitepayRoute =
  ApiPublicWebhooksInfinitepayRouteImport.update({
    id: '/api/public/webhooks/infinitepay',
    path: '/api/public/webhooks/infinitepay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-pensya': typeof AdminPensyaRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/salas': typeof SalasRouteWithChildren
  '/agenda': typeof AuthenticatedAgendaRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/contratos': typeof AuthenticatedContratosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/meu-financeiro': typeof AuthenticatedMeuFinanceiroRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/sublocacao': typeof AuthenticatedSublocacaoRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/assinar/$token': typeof AssinarTokenRoute
  '/cadastro/$token': typeof CadastroTokenRoute
  '/portal/diario': typeof PortalDiarioRoute
  '/portal/evolucao': typeof PortalEvolucaoRoute
  '/portal/financeiro': typeof PortalFinanceiroRoute
  '/portal/relatorios': typeof PortalRelatoriosRoute
  '/processo-publico/$token': typeof ProcessoPublicoTokenRoute
  '/salas/$token': typeof SalasTokenRoute
  '/portal/': typeof PortalIndexRoute
  '/cadastros/modelos': typeof AuthenticatedCadastrosModelosRoute
  '/configuracoes/baterias': typeof AuthenticatedConfiguracoesBateriasRoute
  '/configuracoes/ia': typeof AuthenticatedConfiguracoesIaRoute
  '/configuracoes/instrumentos': typeof AuthenticatedConfiguracoesInstrumentosRoute
  '/configuracoes/protocolos': typeof AuthenticatedConfiguracoesProtocolosRoute
  '/configuracoes/recursos': typeof AuthenticatedConfiguracoesRecursosRoute
  '/configuracoes/referencias': typeof AuthenticatedConfiguracoesReferenciasRoute
  '/pacientes/$id': typeof AuthenticatedPacientesIdRoute
  '/processos/$id': typeof AuthenticatedProcessosIdRoute
  '/equipe/convite/$token': typeof EquipeConviteTokenRoute
  '/portal/convite/$token': typeof PortalConviteTokenRoute
  '/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/pacientes/': typeof AuthenticatedPacientesIndexRoute
  '/processos/': typeof AuthenticatedProcessosIndexRoute
  '/api/public/webhooks/infinitepay': typeof ApiPublicWebhooksInfinitepayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-pensya': typeof AdminPensyaRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/salas': typeof SalasRouteWithChildren
  '/agenda': typeof AuthenticatedAgendaRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/meu-financeiro': typeof AuthenticatedMeuFinanceiroRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/sublocacao': typeof AuthenticatedSublocacaoRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/assinar/$token': typeof AssinarTokenRoute
  '/cadastro/$token': typeof CadastroTokenRoute
  '/portal/diario': typeof PortalDiarioRoute
  '/portal/evolucao': typeof PortalEvolucaoRoute
  '/portal/financeiro': typeof PortalFinanceiroRoute
  '/portal/relatorios': typeof PortalRelatoriosRoute
  '/processo-publico/$token': typeof ProcessoPublicoTokenRoute
  '/salas/$token': typeof SalasTokenRoute
  '/portal': typeof PortalIndexRoute
  '/cadastros/modelos': typeof AuthenticatedCadastrosModelosRoute
  '/configuracoes/baterias': typeof AuthenticatedConfiguracoesBateriasRoute
  '/configuracoes/ia': typeof AuthenticatedConfiguracoesIaRoute
  '/configuracoes/instrumentos': typeof AuthenticatedConfiguracoesInstrumentosRoute
  '/configuracoes/protocolos': typeof AuthenticatedConfiguracoesProtocolosRoute
  '/configuracoes/recursos': typeof AuthenticatedConfiguracoesRecursosRoute
  '/configuracoes/referencias': typeof AuthenticatedConfiguracoesReferenciasRoute
  '/pacientes/$id': typeof AuthenticatedPacientesIdRoute
  '/processos/$id': typeof AuthenticatedProcessosIdRoute
  '/equipe/convite/$token': typeof EquipeConviteTokenRoute
  '/portal/convite/$token': typeof PortalConviteTokenRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesIndexRoute
  '/pacientes': typeof AuthenticatedPacientesIndexRoute
  '/processos': typeof AuthenticatedProcessosIndexRoute
  '/api/public/webhooks/infinitepay': typeof ApiPublicWebhooksInfinitepayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin-pensya': typeof AdminPensyaRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/salas': typeof SalasRouteWithChildren
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/alertas': typeof AuthenticatedAlertasRoute
  '/_authenticated/cadastros': typeof AuthenticatedCadastrosRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/_authenticated/contratos': typeof AuthenticatedContratosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/indicadores': typeof AuthenticatedIndicadoresRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRoute
  '/_authenticated/meu-financeiro': typeof AuthenticatedMeuFinanceiroRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/sublocacao': typeof AuthenticatedSublocacaoRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/assinar/$token': typeof AssinarTokenRoute
  '/cadastro/$token': typeof CadastroTokenRoute
  '/portal/diario': typeof PortalDiarioRoute
  '/portal/evolucao': typeof PortalEvolucaoRoute
  '/portal/financeiro': typeof PortalFinanceiroRoute
  '/portal/relatorios': typeof PortalRelatoriosRoute
  '/processo-publico/$token': typeof ProcessoPublicoTokenRoute
  '/salas/$token': typeof SalasTokenRoute
  '/portal/': typeof PortalIndexRoute
  '/_authenticated/cadastros_/modelos': typeof AuthenticatedCadastrosModelosRoute
  '/_authenticated/configuracoes/baterias': typeof AuthenticatedConfiguracoesBateriasRoute
  '/_authenticated/configuracoes/ia': typeof AuthenticatedConfiguracoesIaRoute
  '/_authenticated/configuracoes/instrumentos': typeof AuthenticatedConfiguracoesInstrumentosRoute
  '/_authenticated/configuracoes/protocolos': typeof AuthenticatedConfiguracoesProtocolosRoute
  '/_authenticated/configuracoes/recursos': typeof AuthenticatedConfiguracoesRecursosRoute
  '/_authenticated/configuracoes/referencias': typeof AuthenticatedConfiguracoesReferenciasRoute
  '/_authenticated/pacientes/$id': typeof AuthenticatedPacientesIdRoute
  '/_authenticated/processos/$id': typeof AuthenticatedProcessosIdRoute
  '/equipe_/convite/$token': typeof EquipeConviteTokenRoute
  '/portal_/convite/$token': typeof PortalConviteTokenRoute
  '/_authenticated/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/_authenticated/pacientes/': typeof AuthenticatedPacientesIndexRoute
  '/_authenticated/processos/': typeof AuthenticatedProcessosIndexRoute
  '/api/public/webhooks/infinitepay': typeof ApiPublicWebhooksInfinitepayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-pensya'
    | '/auth'
    | '/onboarding'
    | '/portal'
    | '/reset-password'
    | '/salas'
    | '/agenda'
    | '/alertas'
    | '/cadastros'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/equipe'
    | '/financeiro'
    | '/importar'
    | '/indicadores'
    | '/marketing'
    | '/meu-financeiro'
    | '/produtos'
    | '/sublocacao'
    | '/tarefas'
    | '/assinar/$token'
    | '/cadastro/$token'
    | '/portal/diario'
    | '/portal/evolucao'
    | '/portal/financeiro'
    | '/portal/relatorios'
    | '/processo-publico/$token'
    | '/salas/$token'
    | '/portal/'
    | '/cadastros/modelos'
    | '/configuracoes/baterias'
    | '/configuracoes/ia'
    | '/configuracoes/instrumentos'
    | '/configuracoes/protocolos'
    | '/configuracoes/recursos'
    | '/configuracoes/referencias'
    | '/pacientes/$id'
    | '/processos/$id'
    | '/equipe/convite/$token'
    | '/portal/convite/$token'
    | '/configuracoes/'
    | '/pacientes/'
    | '/processos/'
    | '/api/public/webhooks/infinitepay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-pensya'
    | '/auth'
    | '/onboarding'
    | '/reset-password'
    | '/salas'
    | '/agenda'
    | '/alertas'
    | '/cadastros'
    | '/contratos'
    | '/dashboard'
    | '/equipe'
    | '/financeiro'
    | '/importar'
    | '/indicadores'
    | '/marketing'
    | '/meu-financeiro'
    | '/produtos'
    | '/sublocacao'
    | '/tarefas'
    | '/assinar/$token'
    | '/cadastro/$token'
    | '/portal/diario'
    | '/portal/evolucao'
    | '/portal/financeiro'
    | '/portal/relatorios'
    | '/processo-publico/$token'
    | '/salas/$token'
    | '/portal'
    | '/cadastros/modelos'
    | '/configuracoes/baterias'
    | '/configuracoes/ia'
    | '/configuracoes/instrumentos'
    | '/configuracoes/protocolos'
    | '/configuracoes/recursos'
    | '/configuracoes/referencias'
    | '/pacientes/$id'
    | '/processos/$id'
    | '/equipe/convite/$token'
    | '/portal/convite/$token'
    | '/configuracoes'
    | '/pacientes'
    | '/processos'
    | '/api/public/webhooks/infinitepay'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-pensya'
    | '/auth'
    | '/onboarding'
    | '/portal'
    | '/reset-password'
    | '/salas'
    | '/_authenticated/agenda'
    | '/_authenticated/alertas'
    | '/_authenticated/cadastros'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contratos'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipe'
    | '/_authenticated/financeiro'
    | '/_authenticated/importar'
    | '/_authenticated/indicadores'
    | '/_authenticated/marketing'
    | '/_authenticated/meu-financeiro'
    | '/_authenticated/produtos'
    | '/_authenticated/sublocacao'
    | '/_authenticated/tarefas'
    | '/assinar/$token'
    | '/cadastro/$token'
    | '/portal/diario'
    | '/portal/evolucao'
    | '/portal/financeiro'
    | '/portal/relatorios'
    | '/processo-publico/$token'
    | '/salas/$token'
    | '/portal/'
    | '/_authenticated/cadastros_/modelos'
    | '/_authenticated/configuracoes/baterias'
    | '/_authenticated/configuracoes/ia'
    | '/_authenticated/configuracoes/instrumentos'
    | '/_authenticated/configuracoes/protocolos'
    | '/_authenticated/configuracoes/recursos'
    | '/_authenticated/configuracoes/referencias'
    | '/_authenticated/pacientes/$id'
    | '/_authenticated/processos/$id'
    | '/equipe_/convite/$token'
    | '/portal_/convite/$token'
    | '/_authenticated/configuracoes/'
    | '/_authenticated/pacientes/'
    | '/_authenticated/processos/'
    | '/api/public/webhooks/infinitepay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminPensyaRoute: typeof AdminPensyaRoute
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  PortalRoute: typeof PortalRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SalasRoute: typeof SalasRouteWithChildren
  AssinarTokenRoute: typeof AssinarTokenRoute
  CadastroTokenRoute: typeof CadastroTokenRoute
  ProcessoPublicoTokenRoute: typeof ProcessoPublicoTokenRoute
  EquipeConviteTokenRoute: typeof EquipeConviteTokenRoute
  PortalConviteTokenRoute: typeof PortalConviteTokenRoute
  ApiPublicWebhooksInfinitepayRoute: typeof ApiPublicWebhooksInfinitepayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-pensya': {
      id: '/admin-pensya'
      path: '/admin-pensya'
      fullPath: '/admin-pensya'
      preLoaderRoute: typeof AdminPensyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salas': {
      id: '/salas'
      path: '/salas'
      fullPath: '/salas'
      preLoaderRoute: typeof SalasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alertas': {
      id: '/_authenticated/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AuthenticatedAlertasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros': {
      id: '/_authenticated/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof AuthenticatedCadastrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos': {
      id: '/_authenticated/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AuthenticatedContratosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicadores': {
      id: '/_authenticated/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof AuthenticatedIndicadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-financeiro': {
      id: '/_authenticated/meu-financeiro'
      path: '/meu-financeiro'
      fullPath: '/meu-financeiro'
      preLoaderRoute: typeof AuthenticatedMeuFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sublocacao': {
      id: '/_authenticated/sublocacao'
      path: '/sublocacao'
      fullPath: '/sublocacao'
      preLoaderRoute: typeof AuthenticatedSublocacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/assinar/$token': {
      id: '/assinar/$token'
      path: '/assinar/$token'
      fullPath: '/assinar/$token'
      preLoaderRoute: typeof AssinarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro/$token': {
      id: '/cadastro/$token'
      path: '/cadastro/$token'
      fullPath: '/cadastro/$token'
      preLoaderRoute: typeof CadastroTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/diario': {
      id: '/portal/diario'
      path: '/diario'
      fullPath: '/portal/diario'
      preLoaderRoute: typeof PortalDiarioRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/evolucao': {
      id: '/portal/evolucao'
      path: '/evolucao'
      fullPath: '/portal/evolucao'
      preLoaderRoute: typeof PortalEvolucaoRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/financeiro': {
      id: '/portal/financeiro'
      path: '/financeiro'
      fullPath: '/portal/financeiro'
      preLoaderRoute: typeof PortalFinanceiroRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/relatorios': {
      id: '/portal/relatorios'
      path: '/relatorios'
      fullPath: '/portal/relatorios'
      preLoaderRoute: typeof PortalRelatoriosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/processo-publico/$token': {
      id: '/processo-publico/$token'
      path: '/processo-publico/$token'
      fullPath: '/processo-publico/$token'
      preLoaderRoute: typeof ProcessoPublicoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salas/$token': {
      id: '/salas/$token'
      path: '/$token'
      fullPath: '/salas/$token'
      preLoaderRoute: typeof SalasTokenRouteImport
      parentRoute: typeof SalasRoute
    }
    '/_authenticated/cadastros_/modelos': {
      id: '/_authenticated/cadastros_/modelos'
      path: '/cadastros/modelos'
      fullPath: '/cadastros/modelos'
      preLoaderRoute: typeof AuthenticatedCadastrosModelosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/': {
      id: '/_authenticated/configuracoes/'
      path: '/'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof AuthenticatedConfiguracoesIndexRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/baterias': {
      id: '/_authenticated/configuracoes/baterias'
      path: '/baterias'
      fullPath: '/configuracoes/baterias'
      preLoaderRoute: typeof AuthenticatedConfiguracoesBateriasRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/ia': {
      id: '/_authenticated/configuracoes/ia'
      path: '/ia'
      fullPath: '/configuracoes/ia'
      preLoaderRoute: typeof AuthenticatedConfiguracoesIaRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/instrumentos': {
      id: '/_authenticated/configuracoes/instrumentos'
      path: '/instrumentos'
      fullPath: '/configuracoes/instrumentos'
      preLoaderRoute: typeof AuthenticatedConfiguracoesInstrumentosRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/protocolos': {
      id: '/_authenticated/configuracoes/protocolos'
      path: '/protocolos'
      fullPath: '/configuracoes/protocolos'
      preLoaderRoute: typeof AuthenticatedConfiguracoesProtocolosRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/recursos': {
      id: '/_authenticated/configuracoes/recursos'
      path: '/recursos'
      fullPath: '/configuracoes/recursos'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRecursosRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/referencias': {
      id: '/_authenticated/configuracoes/referencias'
      path: '/referencias'
      fullPath: '/configuracoes/referencias'
      preLoaderRoute: typeof AuthenticatedConfiguracoesReferenciasRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/pacientes/': {
      id: '/_authenticated/pacientes/'
      path: '/pacientes'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof AuthenticatedPacientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pacientes/$id': {
      id: '/_authenticated/pacientes/$id'
      path: '/pacientes/$id'
      fullPath: '/pacientes/$id'
      preLoaderRoute: typeof AuthenticatedPacientesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processos/': {
      id: '/_authenticated/processos/'
      path: '/processos'
      fullPath: '/processos/'
      preLoaderRoute: typeof AuthenticatedProcessosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processos/$id': {
      id: '/_authenticated/processos/$id'
      path: '/processos/$id'
      fullPath: '/processos/$id'
      preLoaderRoute: typeof AuthenticatedProcessosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/equipe_/convite/$token': {
      id: '/equipe_/convite/$token'
      path: '/equipe/convite/$token'
      fullPath: '/equipe/convite/$token'
      preLoaderRoute: typeof EquipeConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal_/convite/$token': {
      id: '/portal_/convite/$token'
      path: '/portal/convite/$token'
      fullPath: '/portal/convite/$token'
      preLoaderRoute: typeof PortalConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/infinitepay': {
      id: '/api/public/webhooks/infinitepay'
      path: '/api/public/webhooks/infinitepay'
      fullPath: '/api/public/webhooks/infinitepay'
      preLoaderRoute: typeof ApiPublicWebhooksInfinitepayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedConfiguracoesRouteChildren {
  AuthenticatedConfiguracoesBateriasRoute: typeof AuthenticatedConfiguracoesBateriasRoute
  AuthenticatedConfiguracoesIaRoute: typeof AuthenticatedConfiguracoesIaRoute
  AuthenticatedConfiguracoesInstrumentosRoute: typeof AuthenticatedConfiguracoesInstrumentosRoute
  AuthenticatedConfiguracoesProtocolosRoute: typeof AuthenticatedConfiguracoesProtocolosRoute
  AuthenticatedConfiguracoesRecursosRoute: typeof AuthenticatedConfiguracoesRecursosRoute
  AuthenticatedConfiguracoesReferenciasRoute: typeof AuthenticatedConfiguracoesReferenciasRoute
  AuthenticatedConfiguracoesIndexRoute: typeof AuthenticatedConfiguracoesIndexRoute
}

const AuthenticatedConfiguracoesRouteChildren: AuthenticatedConfiguracoesRouteChildren =
  {
    AuthenticatedConfiguracoesBateriasRoute:
      AuthenticatedConfiguracoesBateriasRoute,
    AuthenticatedConfiguracoesIaRoute: AuthenticatedConfiguracoesIaRoute,
    AuthenticatedConfiguracoesInstrumentosRoute:
      AuthenticatedConfiguracoesInstrumentosRoute,
    AuthenticatedConfiguracoesProtocolosRoute:
      AuthenticatedConfiguracoesProtocolosRoute,
    AuthenticatedConfiguracoesRecursosRoute:
      AuthenticatedConfiguracoesRecursosRoute,
    AuthenticatedConfiguracoesReferenciasRoute:
      AuthenticatedConfiguracoesReferenciasRoute,
    AuthenticatedConfiguracoesIndexRoute: AuthenticatedConfiguracoesIndexRoute,
  }

const AuthenticatedConfiguracoesRouteWithChildren =
  AuthenticatedConfiguracoesRoute._addFileChildren(
    AuthenticatedConfiguracoesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAlertasRoute: typeof AuthenticatedAlertasRoute
  AuthenticatedCadastrosRoute: typeof AuthenticatedCadastrosRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRouteWithChildren
  AuthenticatedContratosRoute: typeof AuthenticatedContratosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedIndicadoresRoute: typeof AuthenticatedIndicadoresRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRoute
  AuthenticatedMeuFinanceiroRoute: typeof AuthenticatedMeuFinanceiroRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedSublocacaoRoute: typeof AuthenticatedSublocacaoRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
  AuthenticatedCadastrosModelosRoute: typeof AuthenticatedCadastrosModelosRoute
  AuthenticatedPacientesIdRoute: typeof AuthenticatedPacientesIdRoute
  AuthenticatedProcessosIdRoute: typeof AuthenticatedProcessosIdRoute
  AuthenticatedPacientesIndexRoute: typeof AuthenticatedPacientesIndexRoute
  AuthenticatedProcessosIndexRoute: typeof AuthenticatedProcessosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAlertasRoute: AuthenticatedAlertasRoute,
  AuthenticatedCadastrosRoute: AuthenticatedCadastrosRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRouteWithChildren,
  AuthenticatedContratosRoute: AuthenticatedContratosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedIndicadoresRoute: AuthenticatedIndicadoresRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRoute,
  AuthenticatedMeuFinanceiroRoute: AuthenticatedMeuFinanceiroRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedSublocacaoRoute: AuthenticatedSublocacaoRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
  AuthenticatedCadastrosModelosRoute: AuthenticatedCadastrosModelosRoute,
  AuthenticatedPacientesIdRoute: AuthenticatedPacientesIdRoute,
  AuthenticatedProcessosIdRoute: AuthenticatedProcessosIdRoute,
  AuthenticatedPacientesIndexRoute: AuthenticatedPacientesIndexRoute,
  AuthenticatedProcessosIndexRoute: AuthenticatedProcessosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PortalRouteChildren {
  PortalDiarioRoute: typeof PortalDiarioRoute
  PortalEvolucaoRoute: typeof PortalEvolucaoRoute
  PortalFinanceiroRoute: typeof PortalFinanceiroRoute
  PortalRelatoriosRoute: typeof PortalRelatoriosRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalDiarioRoute: PortalDiarioRoute,
  PortalEvolucaoRoute: PortalEvolucaoRoute,
  PortalFinanceiroRoute: PortalFinanceiroRoute,
  PortalRelatoriosRoute: PortalRelatoriosRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface SalasRouteChildren {
  SalasTokenRoute: typeof SalasTokenRoute
}

const SalasRouteChildren: SalasRouteChildren = {
  SalasTokenRoute: SalasTokenRoute,
}

const SalasRouteWithChildren = SalasRoute._addFileChildren(SalasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminPensyaRoute: AdminPensyaRoute,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  PortalRoute: PortalRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SalasRoute: SalasRouteWithChildren,
  AssinarTokenRoute: AssinarTokenRoute,
  CadastroTokenRoute: CadastroTokenRoute,
  ProcessoPublicoTokenRoute: ProcessoPublicoTokenRoute,
  EquipeConviteTokenRoute: EquipeConviteTokenRoute,
  PortalConviteTokenRoute: PortalConviteTokenRoute,
  ApiPublicWebhooksInfinitepayRoute: ApiPublicWebhooksInfinitepayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
